## Seventh class 26-02-2022

### Numpy - Numerical python

In [2]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [6]:
array1.ndim #

1

In [9]:
array2 = np.array([[1, 2, 3, 4, 5],[6, 5, 7, 8, 9]])

In [10]:
array2.shape

(2, 5)

In [11]:
array2.ndim

2

In [12]:
type(array2)

numpy.ndarray

In [36]:
array2 = np.array([[1, 2, 3,],[6, 5, 7,]], dtype= float)

In [37]:
array2

array([[1., 2., 3.],
       [6., 5., 7.]])

In [38]:
array2.shape

(2, 3)

In [41]:
array2.reshape(3,2)

array([[1., 2.],
       [3., 6.],
       [5., 7.]])

In [42]:
array_reshape = array2.reshape(3,2)

In [43]:
array_reshape.shape

(3, 2)

In [44]:
array_Zero= np.zeros(8)

In [48]:
array_Zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
array_ones = np.ones([3,3], dtype= int)

In [51]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###  Creating an array with existing data

In [53]:
x1 = ([3,5],[5,4],[6,7])
a1=np.asarray(x1, dtype= float)

In [54]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

In [55]:
type(x1)

tuple

### Array from numerical ranges

In [6]:
a1 = np.arange(0,20,3)

In [60]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [63]:
a1 = np.linspace(10,20,5) # last value parts the second value

In [64]:
a1

array([10. , 12.5, 15. , 17.5, 20. ])


## Slicing


In [73]:
list1 = np.arange(10)
array1 = slice(2, 9, 2)
list1[array1]


array([2, 4, 6, 8])

In [77]:
list1 = np.arange(10)
array1 = list1[2: 9: 2]
list1[array1]

array([2, 4, 6, 8])

In [74]:
len(list1)

10

In [78]:
array1

array([2, 4, 6, 8])

In [79]:
array1.shape


(4,)

In [80]:
array1.ndim

1

In [84]:
array1 = np.array([1,2,3])
array2 = np.array([[5,6,7],[8,4,5]])

In [85]:
a = array1*array2

In [86]:
a

array([[ 5, 12, 21],
       [ 8,  8, 15]])

In [87]:
array2.shape


(2, 3)

In [88]:
a.shape

(2, 3)

### Integer indexing

In [97]:
a= np.array([[1,2], [3,4],[5,6]])
b= a[[0,2,2], [0,1,0]] # b= a of row,column
c= a[[1,0,2],[1,0,0]]

In [94]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
print(b)

[1 6 5]


In [98]:
print(c)

[4 1 5]


In [103]:
a= np.array([[2,3,4],[3,4,5],[5,6,7],[5,6,7]])

In [104]:
a

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [115]:
z= a[1:,1:]

In [116]:
z

array([[4, 5],
       [6, 7],
       [6, 7]])

In [119]:
y= a[1:4,[1,2]] # a[ row,column]
y

array([[4, 5],
       [6, 7],
       [6, 7]])

In [120]:
a

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [123]:
z= a[:4,:2]
z

array([[2, 3],
       [3, 4],
       [5, 6],
       [5, 6]])

In [131]:
z1=a[1:2, 1:2]
z1


array([[4]])

In [126]:
a

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [132]:
a[a>5]

array([6, 7, 6, 7])

In [142]:
a=np.array([1,5,np.nan, 8,np.nan,52,65,np.nan])
a


array([ 1.,  5., nan,  8., nan, 52., 65., nan])

In [140]:
a[~np.isnan(a)] # It will remove the nan function

array([ 1.,  5.,  8., 52., 65.])

In [141]:
a[np.isnan(a)] # It will show the nan function

array([nan, nan, nan])

In [144]:
b.dtype

dtype('int32')

## Eighth class (27-02-2022)

In [3]:
import numpy as np

In [9]:
x = np.array([1,2,3,4,])
y = np.array([5,6,7,8])
z = x*y
z

array([ 5, 12, 21, 32])

In [14]:
x1 = np.array([[2,2],[5,3]])
y1= np.array([[5,6],[3,4]])
z1 = x1*y1
z1

array([[10, 12],
       [15, 12]])

In [20]:
x3 = np.array([[2,2],[5,3]])
y3 = ([5,6])
z3 = x3*y3
z3

array([[10, 12],
       [25, 18]])

In [19]:
x4 = np.array([[2,2],[5,3]])
y4 = 5
z4 = x3*y3
z4

array([[10, 10],
       [25, 15]])

In [21]:
z4.T # function.T will transform the rows to column

array([[10, 25],
       [10, 15]])

In [24]:
array1 = np.arange(8).reshape(4,2)
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [25]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
x1 = np.array([[2,2],[5,3]])
y1= np.array([[5,6],[3,4]])
z= np.concatenate((x1,y1))
z


array([[2, 2],
       [5, 3],
       [5, 6],
       [3, 4]])

In [32]:
x = np.array([[1,2,3,4],[7,7,7,7]])
y= np.array([[5,6,7,8],[8,8,8,8]])


In [50]:
z= np.stack((x,y))
z

array([[[1, 2, 3, 4],
        [7, 7, 7, 7]],

       [[5, 6, 7, 8],
        [8, 8, 8, 8]]])

In [34]:
type(z)

numpy.ndarray

In [36]:
z.shape

(4, 2)

In [58]:
x = np.array([[1,2,3,4],[7,7,7,7],[3,4,5,6]])
y= np.array([[5,6,7,8],[8,8,8,8],[5,6,7,8]])
z1= np.stack((x,y), axis= 0) # axis = 0 it doing a operation horizontally
z1

array([[[1, 2, 3, 4],
        [7, 7, 7, 7],
        [3, 4, 5, 6]],

       [[5, 6, 7, 8],
        [8, 8, 8, 8],
        [5, 6, 7, 8]]])

In [59]:
z2= np.stack((x,y), axis= 1) #axis =1 it doing through column wise operation
z2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[3, 4, 5, 6],
        [5, 6, 7, 8]]])

In [63]:
np.vstack((x,y))

array([[1, 2, 3, 4],
       [7, 7, 7, 7],
       [3, 4, 5, 6],
       [5, 6, 7, 8],
       [8, 8, 8, 8],
       [5, 6, 7, 8]])

In [64]:
np.hstack((x,y))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [7, 7, 7, 7, 8, 8, 8, 8],
       [3, 4, 5, 6, 5, 6, 7, 8]])

In [71]:
a= np.arange(9)
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [74]:
array1 = np.array([[1,2,3,4],[7,7,7,7]])
array1

array([[1, 2, 3, 4],
       [7, 7, 7, 7]])

In [78]:
np.append(array1, ([[5,2,8,7],[4,5,6,7]]),axis=0)

array([[1, 2, 3, 4],
       [7, 7, 7, 7],
       [5, 2, 8, 7],
       [4, 5, 6, 7]])

In [77]:
np.append(array1, ([[5,2,8,7],[4,5,6,7]]), axis=1)

array([[1, 2, 3, 4, 5, 2, 8, 7],
       [7, 7, 7, 7, 4, 5, 6, 7]])

In [84]:
np.insert?

In [82]:
x = ([[10,20,30],[40,50,60]])
x




[[10, 20, 30], [40, 50, 60]]

In [83]:
np.insert(x, 2, 10, axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [10, 10, 10]])

In [86]:
np.delete?

In [87]:
x1 = ([[10,20,30],[40,50,60]])

In [90]:
np.delete(x,2,10, axis=0)

TypeError: _delete_dispatcher() got multiple values for argument 'axis'

In [93]:
array1 = np.array([1,2,3,5,6,7,7,7])
np.unique(array1)

array([1, 2, 3, 5, 6, 7])

In [97]:
np.add?

In [ ]:
np.subtract?

In [ ]:
np.mulitiply?

In [99]:
np.divide?

In [98]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[5,6,7],[6,4,9]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[ 6  8 10]
 [10  9 15]]
[[-4 -4 -4]
 [-2  1 -3]]
[[ 5 12 21]
 [24 20 54]]
[[0.2        0.33333333 0.42857143]
 [0.66666667 1.25       0.66666667]]


In [100]:
array1 = np.array([3,5,6])
np.power(array1,3)

array([ 27, 125, 216], dtype=int32)

In [101]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.percentile(array1,50,axis=1)

array([2., 5., 8.])

In [102]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
np.mean?

In [ ]:
np.median

In [ ]:
np.std

In [109]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(array1,axis=0))
print(np.median(array1,axis=0))
print(np.std(array1,axis=0))

[4. 5. 6.]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


## Pandas - Data frame 

In [8]:
import pandas as pd
import numpy as np

In [113]:
a=  np.array([10,2,50,70])
s= pd.Series(a)

In [114]:
type(a)

numpy.ndarray

In [115]:
print(s)

0    10
1     2
2    50
3    70
dtype: int32


In [116]:
type(s)

pandas.core.series.Series

In [117]:
a=  np.array([10,2,50,70])
s=pd.Series(a,index=[10,20,30,40])

In [118]:
s

10    10
20     2
30    50
40    70
dtype: int32

In [124]:
dict1 = {1: 'value1',2: 'value 2',3: 'value 3'}

s=pd.Series(dict1)
s

1     value1
2    value 2
3    value 3
dtype: object

In [126]:
dict2 = {'a': 'value1','b': 'value 2','c': 'value 3'}

s=pd.Series(dict2)
s

a     value1
b    value 2
c    value 3
dtype: object

In [129]:
dict2 = {'a': 0,'b': 1,'c': 3}

s=pd.Series(dict2, index =['b','b','c'])
s

b    1
b    1
c    3
dtype: int64

In [130]:
s[:1]

b    1
dtype: int64

In [131]:
s[:2
 ]

b    1
b    1
dtype: int64

### Nineth class (05-03-2022)


### Creating a dataframe

In [9]:
df = pd.DataFrame()

In [11]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [17]:
a = list(range(10))
df = pd.DataFrame(a)
print(df)


   0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9


In [23]:
list2 = [['Data',1,2],['Data',4,6],['Data',7,8]]
df1 = pd.DataFrame(list2,columns=['column1','column2','column3'])
df1

column1  column2  column3
0    Data        1        2
1    Data        4        6
2    Data        7        8

In [40]:
d1 ={'age':[25,29,30], 'salery':[5000,6000,7000], 'experience':[3,4,6]}
df2= pd.DataFrame(d1, index=[1,2,3])
df2

age  salery  experience
1   25    5000           3
2   29    6000           4
3   30    7000           6

In [41]:
df2[['age', 'experience']]

age  experience
1   25           3
2   29           4
3   30           6

In [44]:
list_col =['age', 'salery']

In [45]:
df2[list_col]

age  salery
1   25    5000
2   29    6000
3   30    7000

In [49]:
df1 = df1.rename(columns={'column2':'age', 'column3':'salery'})


In [47]:
df1

column1  column2  column3
0    Data        1        2
1    Data        4        6
2    Data        7        8

In [48]:
df2

age  salery  experience
1   25    5000           3
2   29    6000           4
3   30    7000           6

In [ ]:
df1 = df1.rename(columns={'50':'CSK', '30':'MI'})

In [50]:
df1

column1  age  salery
0    Data    1       2
1    Data    4       6
2    Data    7       8

In [52]:
df1[0:2]['column1']

0    Data
1    Data
Name: column1, dtype: object

In [53]:
df1.iloc[0:2,0:2][

column1  age
0    Data    1
1    Data    4

In [55]:
df1.loc[:, ['column1','age']]

column1  age
0    Data    1
1    Data    4
2    Data    7

In [84]:
dict5={'Class1': [23,54,67], 'class2':[56,25,67], 'class3':[87,92,45]}
df5= pd.DataFrame(dict5)
df5

Class1  class2  class3
0      23      56      87
1      54      25      92
2      67      67      45

In [85]:
df5['class4']= pd.Series([56,24,56])
df5

Class1  class2  class3  class4
0      23      56      87      56
1      54      25      92      24
2      67      67      45      56

In [86]:
df5['class5'] =df5['class2']+df5['class3']

In [87]:
df5

Class1  class2  class3  class4  class5
0      23      56      87      56     143
1      54      25      92      24     117
2      67      67      45      56     112

In [88]:
del df5['class3']

In [89]:
df5

Class1  class2  class4  class5
0      23      56      56     143
1      54      25      24     117
2      67      67      56     112

In [90]:
df5.drop('class2',axis=1, inplace=True)

In [91]:
df5


Class1  class4  class5
0      23      56     143
1      54      24     117
2      67      56     112

In [92]:
df5.drop(['Class1','class5'], axis=1, inplace=True)
df5

class4
0      56
1      24
2      56

In [101]:
df1=pd.DataFrame([4,'Data',7],[5,6,'Data'],)
df2=pd.DataFrame([5,6,7],[7,8,9])
print(df1)
print(df2)

         0
5        4
6     Data
Data     7
   0
7  5
8  6
9  7


In [97]:
df3=df1.append(df2)
df3

0
5  4
6  6
7  7
7  5
8  6
9  7

In [103]:
Markscard= {'Name': ['Sreenath','Pradeep','Arun'],'Science': [50,60,70],'Maths':[70,60,70],'Language': [50,60,80]}
df22= pd.DataFrame(Markscard,index=[10,11,12])

df22

Name  Science  Maths  Language
10  Sreenath       50     70        50
11   Pradeep       60     60        60
12      Arun       70     70        80

In [106]:
df22['School']=pd.Series(['KV','TCIS','DPS'],index=[10,11,12])
Markscard= {'Name': ['Varun','Kumar','Vijay'],'Science': [50,60,70],'Maths':[70,60,70],'Language': [50,60,80]}


In [105]:
df22

Name  Science  Maths  Language School
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [107]:
df32= pd.DataFrame(Markscard,index=[13,14,15])

In [108]:
df32

Name  Science  Maths  Language
13  Varun       50     70        50
14  Kumar       60     60        60
15  Vijay       70     70        80

In [110]:
df10=pd.concat([df32,df22])

In [111]:
df10

Name  Science  Maths  Language School
13     Varun       50     70        50    NaN
14     Kumar       60     60        60    NaN
15     Vijay       70     70        80    NaN
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [113]:
df10['School'] = np.where(df10['Name'] == 'Kumar', 'KV', df10['School'])


In [114]:
df10

Name  Science  Maths  Language School
13     Varun       50     70        50    NaN
14     Kumar       60     60        60     KV
15     Vijay       70     70        80    NaN
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [115]:
Dict={'Age':[25,26,25,23,30,29,23], 'Name':['Tom','James','Ricky','Vinoth','Steve','Smith','Jack'],'Rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}

In [116]:
df=pd.DataFrame(Dict)

In [117]:
df

Age    Name  Rating
0   25     Tom    4.23
1   26   James    3.24
2   25   Ricky    3.98
3   23  Vinoth    2.56
4   30   Steve    3.20
5   29   Smith    4.60
6   23    Jack    3.80

In [118]:
df.head(3)

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98

In [119]:
df.tail(3)

Age   Name  Rating
4   30  Steve     3.2
5   29  Smith     4.6
6   23   Jack     3.8

In [120]:
df.T

0      1      2       3      4      5     6
Age       25     26     25      23     30     29    23
Name     Tom  James  Ricky  Vinoth  Steve  Smith  Jack
Rating  4.23   3.24   3.98    2.56    3.2    4.6   3.8

In [121]:
df.axes


[RangeIndex(start=0, stop=7, step=1),
 Index(['Age', 'Name', 'Rating'], dtype='object')]

In [122]:
df.dtypes


Age         int64
Name       object
Rating    float64
dtype: object

In [123]:
df.empty

False

In [125]:
df.shape # dimensions of the DF


(7, 3)

In [127]:
df.sum()


Age                                     181
Name      TomJamesRickyVinothSteveSmithJack
Rating                                25.61
dtype: object

In [130]:
import warnings
warnings.filterwarnings('ignore')

In [131]:
df.mean()

Age       25.857143
Rating     3.658571
dtype: float64

In [132]:
df.median()

Age       25.0
Rating     3.8
dtype: float64

In [133]:
df['Age'].mode()

0    23
1    25
dtype: int64

In [134]:
df.std()

Age       2.734262
Rating    0.698628
dtype: float64

In [135]:
df.count()

Age       7
Name      7
Rating    7
dtype: int64

In [136]:
df['Age'].min()

23

In [137]:
df['Age'].max()

30

In [138]:
df.describe()

Age    Rating
count   7.000000  7.000000
mean   25.857143  3.658571
std     2.734262  0.698628
min    23.000000  2.560000
25%    24.000000  3.220000
50%    25.000000  3.800000
75%    27.500000  4.105000
max    30.000000  4.600000

In [9]:
dic={'col1':[20,50,40,60,80],'col2':[80,60,40,20,55],'col3':[20,80,55,66,33]}
df1=pd.DataFrame(dic)
df1

col1  col2  col3
0    20    80    20
1    50    60    80
2    40    40    55
3    60    20    66
4    80    55    33

In [144]:
df1.apply(np.mean)

col1    50.0
col2    51.0
col3    50.8
dtype: float64

In [10]:
df1.apply(lambda x:x.max() -x.min())

col1    60
col2    60
col3    60
dtype: int64

In [12]:
df1.rename(columns ={'Col1': 'Columns1', 'Col2': 'Columns2', 'Col3': 'Columns3'}, inplace = True)

In [13]:
df1

col1  col2  col3
0    20    80    20
1    50    60    80
2    40    40    55
3    60    20    66
4    80    55    33

## Tenth Class (06-03-2020)

### Creating the DataFrame by using Random number

In [10]:
df = pd.DataFrame(np.random.randn(5, 2), index=[1,5,3,2,4],columns=['Columns1','Columns2'])

In [16]:
df

Columns1  Columns2
1  1.028044 -0.279642
5  1.838296  0.491557
3 -1.162957 -0.135359
2  0.846494  0.264441
4  0.312401 -2.246536

In [12]:
np.random.randn(5, 2)

array([[ 1.84622361, -0.26483824],
       [ 0.08235536,  1.30942788],
       [-0.95849412, -0.06806472],
       [-0.95205884, -2.01240661],
       [-1.34746906, -0.91925396]])

### Sort the indexes

In [13]:
df.sort_index()

Columns1  Columns2
1 -0.076894  1.017425
2  2.499336 -0.639940
3 -0.251097 -0.523978
4  2.505423  2.183520
5  0.580196 -1.160741

In [14]:
df.sort_index(ascending=False)

Columns1  Columns2
5  0.580196 -1.160741
4  2.505423  2.183520
3 -0.251097 -0.523978
2  2.499336 -0.639940
1 -0.076894  1.017425

### Sorting columns

In [18]:
df.sort_index(axis=1) # it's 

Columns1  Columns2
1 -0.076894  1.017425
5  0.580196 -1.160741
3 -0.251097 -0.523978
2  2.499336 -0.639940
4  2.505423  2.183520

In [19]:
df.sort_values(by = 'Columns1') # it's acsending column values

Columns1  Columns2
3 -0.251097 -0.523978
1 -0.076894  1.017425
5  0.580196 -1.160741
2  2.499336 -0.639940
4  2.505423  2.183520

In [20]:
df.sort_values(by = 'Columns1', ascending = False)

Columns1  Columns2
4  2.505423  2.183520
2  2.499336 -0.639940
5  0.580196 -1.160741
1 -0.076894  1.017425
3 -0.251097 -0.523978

### loc

In [21]:
df.loc[]

SyntaxError: invalid syntax (Temp/ipykernel_11124/2240581962.py, line 1)

In [22]:
dict3 = {'Age':[25,26,25,23,30,29,23],'Name':['Tom','James','Ricky','Vin','Steve','Smith','Jack'],'Rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}

In [23]:
df=pd.DataFrame(dict3)

In [24]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

### loc- Subsetting

In [25]:
df.loc[:3,['Age','Name']]


Age   Name
0   25    Tom
1   26  James
2   25  Ricky
3   23    Vin

In [26]:
df.loc[:3,['Age','Name','Rating']]

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56

### Changing the Index

In [27]:
df.index= ['a','b','c','d','e','f','g']

In [28]:
df

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98
d   23    Vin    2.56
e   30  Steve    3.20
f   29  Smith    4.60
g   23   Jack    3.80

In [29]:
df.take([0,2,5])

Age   Name  Rating
a   25    Tom    4.23
c   25  Ricky    3.98
f   29  Smith    4.60

In [40]:
df.loc['b':'e',['Age','Name']]

Age   Name
b   26  James
c   25  Ricky
d   23    Vin
e   30  Steve

### iloc

In [30]:
df.iloc[0:4,0:2]

Age   Name
a   25    Tom
b   26  James
c   25  Ricky
d   23    Vin

In [31]:
df.iloc[:4]

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98
d   23    Vin    2.56

### Handling the missing Data

In [33]:
df1 = pd.DataFrame(np.random.randn(5,3), index=['a','b','c','d','e',], columns =['One','Two','Three'])

In [34]:
df1

One       Two     Three
a -1.300210 -0.792199 -0.122520
b -1.112177  0.342818 -1.091229
c  0.926800  1.734381 -1.348684
d  1.156098 -0.993045  1.663193
e -0.742217  0.251435  0.031799

In [35]:
df1= df1.reindex(['a','b','c','d','e','f','g','h'])

In [36]:
df1

One       Two     Three
a -1.300210 -0.792199 -0.122520
b -1.112177  0.342818 -1.091229
c  0.926800  1.734381 -1.348684
d  1.156098 -0.993045  1.663193
e -0.742217  0.251435  0.031799
f       NaN       NaN       NaN
g       NaN       NaN       NaN
h       NaN       NaN       NaN

### Null and Not Null function

In [37]:
df1['Two'].isnull()

a    False
b    False
c    False
d    False
e    False
f     True
g     True
h     True
Name: Two, dtype: bool

In [38]:
df1['One'].notnull()

a     True
b     True
c     True
d     True
e     True
f    False
g    False
h    False
Name: One, dtype: bool

In [39]:
df1['Three'].isnull().sum()

3

In [41]:
df1[df1['One'].notnull()]

One       Two     Three
a -1.300210 -0.792199 -0.122520
b -1.112177  0.342818 -1.091229
c  0.926800  1.734381 -1.348684
d  1.156098 -0.993045  1.663193
e -0.742217  0.251435  0.031799

### Filling missing Data

In [43]:
df1['One'].fillna(0)

a   -1.300210
b   -1.112177
c    0.926800
d    1.156098
e   -0.742217
f    0.000000
g    0.000000
h    0.000000
Name: One, dtype: float64

In [44]:
df1.fillna(1, inplace=True)

In [45]:
df1


One       Two     Three
a -1.300210 -0.792199 -0.122520
b -1.112177  0.342818 -1.091229
c  0.926800  1.734381 -1.348684
d  1.156098 -0.993045  1.663193
e -0.742217  0.251435  0.031799
f  1.000000  1.000000  1.000000
g  1.000000  1.000000  1.000000
h  1.000000  1.000000  1.000000

In [48]:
df1.loc['d':'f']=pd.Series({'One':np.NaN, 'TWO':np.NaN,'Three':np.NaN})

In [49]:
df1

One       Two     Three
a -1.300210 -0.792199 -0.122520
b -1.112177  0.342818 -1.091229
c  0.926800  1.734381 -1.348684
d       NaN       NaN       NaN
e       NaN       NaN       NaN
f       NaN       NaN       NaN
g  1.000000  1.000000  1.000000
h  1.000000  1.000000  1.000000

In [51]:
df1.dropna()

One       Two     Three
a -1.300210 -0.792199 -0.122520
b -1.112177  0.342818 -1.091229
c  0.926800  1.734381 -1.348684
g  1.000000  1.000000  1.000000
h  1.000000  1.000000  1.000000

### Aggregation

In [53]:
df

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98
d   23    Vin    2.56
e   30  Steve    3.20
f   29  Smith    4.60
g   23   Jack    3.80

In [60]:
df['Score']=[70,80,90,95,100,95,75]

In [61]:
df

Age   Name  Rating  Score
a   25    Tom    4.23     70
b   26  James    3.24     80
c   25  Ricky    3.98     90
d   23    Vin    2.56     95
e   30  Steve    3.20    100
f   29  Smith    4.60     95
g   23   Jack    3.80     75

In [62]:
df.groupby(['Age'])['Score'].sum()

Age
23    170
25    160
26     80
29     95
30    100
Name: Score, dtype: int64

In [70]:
df.groupby(['Age'])['Score','Rating'].mean().reset_index()

C:\Users\Laksh\AppData\Local\Temp/ipykernel_11124/1471962803.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['Age'])['Score','Rating'].mean().reset_index()


Age  Score  Rating
0   23   85.0   3.180
1   25   80.0   4.105
2   26   80.0   3.240
3   29   95.0   4.600
4   30  100.0   3.200

### Multiple Aggregations

In [72]:
df.groupby(['Age'])['Score','Rating'].agg([np.mean,np.median]).reset_index()

C:\Users\Laksh\AppData\Local\Temp/ipykernel_11124/3748192966.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['Age'])['Score','Rating'].agg([np.mean,np.median]).reset_index()


Age  Score        Rating       
        mean median   mean median
0  23   85.0   85.0  3.180  3.180
1  25   80.0   80.0  4.105  4.105
2  26   80.0   80.0  3.240  3.240
3  29   95.0   95.0  4.600  4.600
4  30  100.0  100.0  3.200  3.200

### Merge -> join

In [81]:
df_left=pd.DataFrame({'Name':['Alex','Amy','Alen','Alice','Ayoung'],'Id':[1,2,3,4,5],'Subject Id': ['Sub1','Sub2','Sub3','Sub4','Sub5']})

In [76]:
df_left

Name  ID Subject Id
0    Alex   1       Sub1
1     Amy   2       Sub2
2    Alen   3       Sub3
3   Alice   4       Sub4
4  Ayoung   5       Sub5

In [85]:
df_right=pd.DataFrame({'Name':['Billy','Brian','Bran','Bryce','Betty'],'Id':[1,2,3,4,5],'Subject Id':['Sub2','Sub4','Sub3','Sub6','Sub5']})

In [86]:
df_right

Name  Id Subject Id
0  Billy   1       Sub2
1  Brian   2       Sub4
2   Bran   3       Sub3
3  Bryce   4       Sub6
4  Betty   5       Sub5

### Merge with One Key

In [87]:
pd.merge(df_left,df_right, on='Id')

Name_x  Id Subject Id_x Name_y Subject Id_y
0    Alex   1         Sub1  Billy         Sub2
1     Amy   2         Sub2  Brian         Sub4
2    Alen   3         Sub3   Bran         Sub3
3   Alice   4         Sub4  Bryce         Sub6
4  Ayoung   5         Sub5  Betty         Sub5

In [88]:
pd.merge(df_left,df_right, on=['Id','Subject Id'])

Name_x  Id Subject Id Name_y
0    Alen   3       Sub3   Bran
1  Ayoung   5       Sub5  Betty

### Merger operation using 'how'

In [92]:
df_left.merge(df_right, on='Subject Id', how ='left')

Name_x  Id_x Subject Id Name_y  Id_y
0    Alex     1       Sub1    NaN   NaN
1     Amy     2       Sub2  Billy   1.0
2    Alen     3       Sub3   Bran   3.0
3   Alice     4       Sub4  Brian   2.0
4  Ayoung     5       Sub5  Betty   5.0

In [90]:
df_left

Name  Id Subject Id
0    Alex   1       Sub1
1     Amy   2       Sub2
2    Alen   3       Sub3
3   Alice   4       Sub4
4  Ayoung   5       Sub5

In [91]:
df_right

Name  Id Subject Id
0  Billy   1       Sub2
1  Brian   2       Sub4
2   Bran   3       Sub3
3  Bryce   4       Sub6
4  Betty   5       Sub5

### Left outer join-> how='left'

In [93]:
df_left.merge(df_right, on='Subject Id', how ='left')

Name_x  Id_x Subject Id Name_y  Id_y
0    Alex     1       Sub1    NaN   NaN
1     Amy     2       Sub2  Billy   1.0
2    Alen     3       Sub3   Bran   3.0
3   Alice     4       Sub4  Brian   2.0
4  Ayoung     5       Sub5  Betty   5.0

### Concat

In [94]:
pd.concat([df_left,df_right])

Name  Id Subject Id
0    Alex   1       Sub1
1     Amy   2       Sub2
2    Alen   3       Sub3
3   Alice   4       Sub4
4  Ayoung   5       Sub5
0   Billy   1       Sub2
1   Brian   2       Sub4
2    Bran   3       Sub3
3   Bryce   4       Sub6
4   Betty   5       Sub5

In [95]:
pd.concat([df_left,df_right],axis=1) #column wise operation

Name  Id Subject Id   Name  Id Subject Id
0    Alex   1       Sub1  Billy   1       Sub2
1     Amy   2       Sub2  Brian   2       Sub4
2    Alen   3       Sub3   Bran   3       Sub3
3   Alice   4       Sub4  Bryce   4       Sub6
4  Ayoung   5       Sub5  Betty   5       Sub5

In [97]:
pd.concat([df_left,df_right]) # Row wise operation

Name  Id Subject Id
0    Alex   1       Sub1
1     Amy   2       Sub2
2    Alen   3       Sub3
3   Alice   4       Sub4
4  Ayoung   5       Sub5
0   Billy   1       Sub2
1   Brian   2       Sub4
2    Bran   3       Sub3
3   Bryce   4       Sub6
4   Betty   5       Sub5

In [98]:
pd.concat([df_left,df_right],ignore_index= True)

Name  Id Subject Id
0    Alex   1       Sub1
1     Amy   2       Sub2
2    Alen   3       Sub3
3   Alice   4       Sub4
4  Ayoung   5       Sub5
5   Billy   1       Sub2
6   Brian   2       Sub4
7    Bran   3       Sub3
8   Bryce   4       Sub6
9   Betty   5       Sub5

### Append operation to demonstrate the concatenation

In [101]:
df_left.append(df_right)

Name  Id Subject Id
0    Alex   1       Sub1
1     Amy   2       Sub2
2    Alen   3       Sub3
3   Alice   4       Sub4
4  Ayoung   5       Sub5
0   Billy   1       Sub2
1   Brian   2       Sub4
2    Bran   3       Sub3
3   Bryce   4       Sub6
4   Betty   5       Sub5